 $(window).on("load", function(){



 $('.preloader').fadeOut(1000, function(){
     
     $(this).parent().fadeOut();
     
     
 });

    
});





$(document).ready(function () {
	
			    $(".language").click(function(){
               $(".dropdown-conutry").slideToggle();
                   }) ;
    

         $(".join-us-content p").matchHeight();
             $(".category-item").matchHeight();
    
             $(".footer-menu h5").matchHeight();
             $(".footer-menu ul").matchHeight();




});
